name: clever2-test.vsmart00.com

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Enter Branch or Tag name to create build image"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: check to location
        run: |
          ls -al
          cd ..
          ls -al

      - name: Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: clientinfo
          tags: clever2-test-master
          containerfiles: |
            ./Dockerfile

      - name: Push
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ secrets.DOCKERHUB_USERNAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}